ec1/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.topfunc,name="top"),
    path('shop/', include('shop.urls')), 
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('purchase/', include('purchase.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),
    path("guide/",views.howtofunc,name="howto"),
    path("asct/",views.asctfunc,name="asct"),
    path("privacy-policy/",views.ppfunc,name="pp"),
    path("faq/",views.faqfunc,name="faq"),
    path("aboutus/",views.aboutfunc,name="aboutus"),
     path('contactform/',views.contactfunc,name="sendmail"),
    path('donecontact/',views.contactcomplete,name="donecontact"),

]

if settings.DEBUG:
    # staticファイルとmediaファイルのドキュメントルートを設定
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchase/urls.py
from django.urls import path
from . import views

app_name = 'purchase'

urlpatterns = [
    path('',views.purchasefunc, name='purchase'),
    path('complate/',views.complete,name="complate"),
    path('payment/', views.create_payment, name='payment'),
   
   
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('',views.allProdCat,name="allProdCat"),
    path("<slug:c_slug>/",views.allProdCat,name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

purchase/models.py
from django.db import models

# Create your models here.

class Sale(models.Model):

    familyname_kanji = models.CharField('苗字漢字', max_length=50)
    lastname_kanji = models.CharField('名前漢字', max_length=50)
    familyname_kana = models.CharField('苗字カナ', max_length=50)
    lastname_kana = models.CharField('名前カナ', max_length=50)
    zipCode = models.CharField('郵便番号', max_length=255)
    state = models.CharField('都道府県', max_length=255)
    address = models.CharField('住所', max_length=255)
    buildingName = models.CharField('建物名', max_length=255)
    # phoneNumber = models.PhoneNumberField("電話番号" , max_length=255)
    phoneNumber = models.CharField("電話番号" , max_length=25)
    mailAdrress = models.CharField('メールアドレス', max_length=255)
    stripeCode = models.CharField("ストライプコード", max_length=50 , blank=True)
    salesPrice = models.IntegerField()
    taxPrice = models.IntegerField()
    shippingPrice = models.IntegerField()
    discountPrice = models.IntegerField()
    created = models.DateTimeField('販売日', auto_now_add=True)
    available = models.BooleanField('発送済み',default=False)

    class Meta:
        verbose_name_plural = "売上データ"

purchase/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from shop.models import Product
from cart.models import Cart, CartItem
from .models import Sale
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from order.models import Order, OrderItem
from django.http import JsonResponse, HttpResponse
# 追加分
import json
from django.core.mail import send_mail
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.core.mail import send_mail, EmailMessage
from django.template.loader import render_to_string
import datetime


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def purchasefunc(request):
    sub_total = 0
    tax = 0
    counter = 0
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            tax += (cart_item.product.inTax * cart_item.quantity)
            sub_total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    shipping = 0
    discount = 0
    all_total = sub_total + shipping - discount
    return render(request,"purchase.html",dict(all_total=all_total,sub_total = sub_total, discount=discount ,shipping=shipping,tax=tax))

def complete(request):
    return render(request,"thx.html")

def sendMail(email,name,date,pur_id,state,address,building,total,tax,shipping,all_total,cart):
    subject = "【KUMAGAI kitchen】お買い上げありがとうございました。"
    # 送信元
    from_email = "kitchen@kumagaicorp.jp"
    recipient_list = [
        email,
    ]
    # recipient_list.append(email)
    print(recipient_list)
    # パラメータ
    context = {
        "name" : name,
        "date":date,
        "pur_id":pur_id,
        "state":state,
        "address":address,
        "building":building,
        "total":total,
        "tax":tax,
        "shipping":shipping,
        "all_total":all_total,
        "cart_items":cart,
    }
    msg_plain = render_to_string('mailset.txt', context)
    # HTMLメール用テンプレート
    msg_html = render_to_string('mailset.html', context)
    send_mail(subject, msg_plain,from_email, recipient_list, html_message=msg_html,)

# ここからストライプ用
stripe.api_key = settings.STRIPE_SECRET_KEY
def create_payment(request):
    tax =0
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            tax += (cart_item.product.inTax * cart_item.quantity)

    except ObjectDoesNotExist:
        pass

    if request.method == "POST":
        req_json = json.loads(request.body)
        totalPrice = req_json['totalPrice']
        sub_total_price = req_json['sub_totalPrice']
        # tax = req_json['taxPrice']
        shippingPrice = req_json['shippingPrice']
        discountPrice = req_json['discountPrice']
        email =req_json['email']
        name= req_json['family_kanji'] + " "+req_json['last_kanji']
        now = datetime.datetime.now()
        date=now.strftime('%Y年%m月%d日')
        state = req_json['todoufuken']
        address = req_json['shikuchouson']
        building = req_json['buildingname']
        
        
        if len(totalPrice) > 3:
            totalPrice = totalPrice.replace(",","")
        if len(shippingPrice) > 3:
            shippingPrice = shippingPrice.replace(",","")
        if len(discountPrice) > 3:
            discountPrice = discountPrice.replace(",","")
            
        try:    
            customer = stripe.Customer.create(
                name=req_json['family_kana'] + " "+req_json['last_kana'],
                email=req_json['email'],
                )
            intent = stripe.PaymentIntent.create(
                amount=int(totalPrice),
                currency='jpy',
                customer=customer['id'],
                setup_future_usage='off_session',
                metadata={
                    "product_id": "meta data"
                },
                payment_method_types=['card'],
            )
            
           
            sale_history = Sale(
                familyname_kanji=req_json['family_kanji'],
                lastname_kanji=req_json['last_kanji'],
                familyname_kana=req_json['family_kana'],
                lastname_kana=req_json['last_kana'],
                zipCode=req_json['yuubin'],
                state=req_json['todoufuken'],
                address=req_json['shikuchouson'],
                buildingName=req_json['buildingname'],
                phoneNumber=req_json['tel'],
                mailAdrress=req_json['email'],
                stripeCode=customer['id'],
                salesPrice=int(totalPrice),
                taxPrice=int(tax),
                shippingPrice=int(shippingPrice),
                discountPrice=int(discountPrice),
            )
            sale_history.save()
            p_id = intent['id']
            pur_id = p_id.split('_')[1]
            order_details = Order.objects.create(
                            token = intent['id'],
                            total = int(totalPrice),
                            emailAddress =req_json['email'],
                            billingName = req_json['family_kana'] + " "+req_json['last_kana'],
                            billingAddress1 = req_json['shikuchouson']+" "+req_json['buildingname'],
                            billingCity = req_json['todoufuken'],
                            billingPostcode = req_json['yuubin'],
                            billingCountry = "JPN",
                            shippingName = req_json['family_kana'] + " "+req_json['last_kana'],
                            shippingAddress1 = req_json['shikuchouson']+" "+req_json['buildingname'],
                            shippingCity = req_json['todoufuken'],
                            shippingPostcode = req_json['yuubin'],
                            shippingCountry = "JPN",
                        )
            order_details.save()
            
            print("here333")
            price_fv = "{:,}".format(int(totalPrice))
            sendMail(email,name,date,pur_id,state,address,building,sub_total_price,tax,shippingPrice,str(price_fv),cart_items)
            print('hereeeeeeee')
            for order_item in cart_items:
                oi = OrderItem.objects.create(
                        product = order_item.product.name,
                        quantity = order_item.quantity,
                        price = order_item.product.price,
                        order = order_details
                    )
                oi.save()
                products = Product.objects.get(id=order_item.product.id)
                products.stock = int(order_item.product.stock - order_item.quantity)
                products.save()
                order_item.delete()

            
            return JsonResponse({
                'clientSecret': intent['client_secret']
            })

        except Exception as e:
            return JsonResponse({ 'error': str(e) })

purchase/templates/mailset.html
<!DOCTYPE html>
<html lang="ja">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thankyou mail </title>
    <style type="text/css">
        body{
        margin:0;
        padding:0;
        background-color:#fff
        }    
        .ptag{
            margin: 0;
            line-height: 1.5rem;
        }
        span{
            margin-left: 30px;
            font-weight: bold;
            color: #252525;
        }
        a{
            text-decoration: none;
        }
        h3{
            background-color: #f6f4ef;
        }
        .mail-content{
            /* background-color: #f6f4ef; */
            min-width:820px ;
            color: #252525;
            width: 100%;
            height: auto;
            margin-top: 100px;
        }
        .mail-top{
            margin: 0 auto;
            width: 80%;
            display: -webkit-flex;
            display: flex;
            -webkit-justify-content: space-between;
            justify-content: space-between;
            /* background-color: #f6f4ef; */
            border-bottom: white 2px solid;
        }
        .mail-logo{
            width: 100px;
            height: 100px;   
        }
        .mail-logo > img{
            width: 100px;
            height: 100px;
            justify-content: center;
        }
        .mail-recipt{
            width: 100px;
            height: 100px;
            text-align: right;
            font-size: 2rem;
            vertical-align:center;          
        }
        .recipt-title{
            position: absolute;
            bottom: 0;
        }
        .mail-info{
            margin: 0 auto;
            background-color: #f6f4ef;
            width: 80%;
            display: flex;
            border-bottom: white 2px solid;
        }
        .left-side{
            height: auto;
            min-height: 200px;
            width: 60%;
            background-color: #f6f4ef;
        }
        .mail-customer-info{
            /* padding-left: 30px; */
            height: 100%;
        }
        .info-item{
            min-height: 33%;
            height: auto;
        }
        .info-item:nth-child(2){
            border-top: white 2px solid;
            border-bottom: white 2px solid;
        }
        .right-side{
            width: 40%;
            border-left: white 2px solid;
        }
        .mail-detail{
            margin: 0 auto;
            /* background-color: #f6f4ef; */
            width: 80%;
            min-height: 200px;
        }
        .mail-customer-info ,.address-list, .product-list{
            list-style: none;
            margin: 0;
            padding: 0;
        }
        .mail-amount{
            width: 80%;
            height: 120px;
            margin: 0 auto;
            border-top: #f6f4ef 2px solid;
            border-bottom: #f6f4ef 2px solid;
        }
        .mail-footer{
            width: 80%;
            margin: 0 auto;
            text-align: center;
        }
        .mail-product-list{
            width: 100%;
            min-height: 150px;
            height: auto;
        }
        .product{
            width: 90%;
            margin: 0 auto;
            display: -webkit-flex;
            display: flex;
            -webkit-justify-content: space-between;
            justify-content: space-between;
        }
        .product-list{
            width: 100%;    
        }
        .product-info{
            display: flex;
        }
        .product-info-area{
            margin-top: 20px;
            margin-left: 30px;
        }
        .product-pic{
            width: 100px;
            margin: 0;
        }
        .product-pic > img{
            width: 100px;
            height: 100px;
            object-fit: cover;
            border-radius: 5px;
        }
        .product-name{
            font-size: 1.5rem;
        }
        .product-review{
            display:initial;
        }
        .product-price{
            margin-top: 20px;
        }
        .mail-amount{
            width: 80%;
            margin: 0 auto;
            text-align: right;
        }
    </style>
    <!--<link rel="stylesheet" type="text/css" href="mail.css">-->
</head>
<body>
    <div class="mail-content">
        <div class="mail-top">
            <div class="mail-logo"><img src="kumagai1.png" alt=""></div>
            <div class="mail-recipt"><div calss="recipt-title"></div></div>
        </div>
        <div class="mail-info">
            <div class="left-side">
                <ul class="mail-customer-info">
                    <li class="info-item"><p class="ptag"> &nbsp;お名前</p><span>{{ name }}</span></li>
                    <li class="info-item"><p class="ptag"> &nbsp;購入日</p><span>{{ date }}</span></li>
                    <li class="info-item"><p class="ptag"> &nbsp;ご注文番号</p><span>{{ pur_id }}</span></li>
                    
                </ul>
            </div>
            <div class="right-side">
                <div class="address-title">お届け先</div>
                <div class="address-info">
                    <ul class="address-list">
                        <li class="address1"><p class="ptag"> &nbsp;都道府県</p><span>{{ state }}</span></li>
                        <li class="address2"><p class="ptag"> &nbsp;住所</p><span>{{ address }}</span></li>
                        <li class="address3"><p class="ptag"> &nbsp;建物名</p><span>{{ building }}</span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="mail-detail"><h3>ご購入商品</h3>
            <div class="mail-product">
                <div class="mail-product-list">
                    <ul class="product-list">
                        {% for cart_item in cart_items%}
                        <li class="product">
                            <div class="product-info">
                                <div class="product-pic"><img src="{% static cart_item.product.image.url %}" alt="{{cart_item.product.name}}"></div>
                                <div class="product-info-area">
                                    <div class="product-name"><span>{{cart_item.product.name}}</span></div>
                                    <div class="product-review"><a href="#"><span class="review">レビューを書く</span></a></div>
                                </div>
                            </div>
                            <div class="product-price"><span>{{cart_item.sub_total}}</span>円</div>        
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="mail-amount">
            <div class="mail-subtotal">商品小計<span>{{ total }}</span>円</div>
            <div class="mail-tax">内消費税<span>{{ tax  }}</span>円</div>
            <div class="mail-shipping">配送料<span>{{ shipping }}</span>円</div>
            <div class="mail-total-price"><h3>合計<span>{{ all_total }}</span>円</h3></div>
        </div>
        <div class="mail-footer">All right reserved KUMAGAICORPRATION</div>
    </div>
    
    
</body>
</html>

purchase/templates/purchase.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
    This is the shopping cart page.. Proced to review your items and place the order.
{% endblock %}
{% block title %}KUMAGAI KITCHEN | お客様情報入力{% endblock %}
{% block content %}
   
      <div class="customer_form main-area-fadein">
        <div class="form-area">
          <div class="stuff">
            <div class="form-title">
              <h2>お客様情報入力</h2>
            </div>
            <form action="{% url 'purchase:payment' %}" method="POST" id="payment-form">
             {% csrf_token %}
            <div class="name-area-kanji">
              <div class="textBox name-textbox">
                <input  class="text"  id="family_kanji" name="family_kanji" type="textbox" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
                <label class="label">姓</label>
                <label class="error"></label>
              </div>
              <div class="textBox name-textbox">
                <input  class="text"   id="last_kanji" name="last_kanji" type="textbox" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
                <label class="label">名</label>
                <label class="error"></label>
              </div>
            </div>
            <div class="name-area-kana">
              <div class="textBox name-textbox">
                <input  class="text"  id="family_kana" name="family_kana" type="textbox" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
                <label class="label">セイ</label>
                <label class="error"></label>
              </div>
              <div class="textBox name-textbox">
                <input  class="text"   id="last_kana" name="last_kana" type="textbox" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
                <label class="label">メイ</label>
                <label class="error"></label>
              </div>
            </div>
            <div class="textBox">
              <input class="text" id="yuubin" name="yuubin" type="text" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
              <label class="label">郵便番号</label>
              <label class="error"></label>
            </div>
            <div class="textBox">
              <input class="text" id="todoufuken" name="todoufuken" type="text" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
              <label class="label">都道府県</label>
              <label class="error"></label>
            </div>
            <div class="textBox">
              <input class="text" id="shikuchouson" name="shikuchouson" type="text" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
              <label class="label">住所</label>
              <label class="error"></label>
            </div>
            <div class="textBox">
              <input class="text" id="buildingname" name="buildingname" type="text" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
              <label class="label">建物名</label>
              <label class="error"></label>
            </div>
            <div class="textBox">
              <input class="text" id="tel" name="tel" type="tel" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
              <label class="label">電話番号</label>
              <label class="error"></label>
            </div>
            <div class="textBox">
              <input class="text" id="email" name="email" type="email" placeholder="" onkeyup="this.setAttribute('value', this.value);" value=""/>
              <label class="label">メールアドレス</label>
              <label class="error"></label>
            </div>
           {% comment %} </form> {% endcomment %}
          </div>
        </div>
       
        <div class="credit-area">
            <div class="credit-form-area">
              <div class="payment-summary">
                  <table class="summary-table">
                    <tr>
                      <td>小計</td>
                      <td></td>
                      <td><span id="sub_total_price">{{ sub_total }}</span>円<span class="tax-in-text">(税込)</span></td>
                    </tr>
                    <tr>
                      <td></td>
                      <td> 内消費税</td>
                      <td><span id="taxPrice">{{ tax }}</span>円</td>
                    </tr>
                    <tr>
                      <td>配送料</td>
                      <td></td>
                      <td><span id="price_shipping">{{ shipping }}</span>円</td>
                    </tr>
                    <tr>
                      <td>割引</td>
                      <td>記念割引</td>
                      <td>-<span id="discount-price"> {{ discount }}</span>円</td>
                    </tr>
                  </table>
              </div>
              <div class="credit-total-price">
                <h1 class="total" id="credit-total-amount">合計:<span id="total-price">{{ all_total }}</span>円<span class="tax-in-text"><br/>(税込)</span></h1>
              </div>
              <div class="credit-form">
                  <div id="card-element"><!--Stripe.js injects the Card Element--></div>
                  <p id="card-error" role="alert"></p>
                  <button id="submit"　type="submit">
                    <div class="spinner hidden" id="spinner"></div>
                    <span id="button-text">注文の確定</span>
                  </button>
                  
                  <p class="result-message hidden">
                    
                    <a href="" target="_blank">T</a>
                  </p>
                </form>
              </div>
             
            </div>
        </div>        
      </div>

    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'js/purchase.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
      

      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      // Create an instance of the Stripe object with your publishable API key
      //var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
      var stripe = Stripe("pk_test_51INrEmDYWRtgxnI5bKNutTqsylocbo56vp7IHiGYcLsuF5qsKcVLkm4K7NdtqhaQIZSafCTfEirQnbbTnPCYyIoM00LemwOdx5");
      document.querySelector("button").disabled = true;

      var elements = stripe.elements();
      var style = {
        base: {
          hidePostalCode: true,
          color: "#32325d",
          fontFamily: 'Arial, sans-serif',
          fontSmoothing: "antialiased",
          fontSize: "16px",
          "::placeholder": {
            color: "#32325d"
          }
        },
        invalid: {
          fontFamily: 'Arial, sans-serif',
          color: "#fa755a",
          iconColor: "#fa755a"
        }
      };
      var card = elements.create("card", { style: style });
      // Stripe injects an iframe into the DOM
      card.mount("#card-element");
      card.on("change", function (event) {
        // Disable the Pay button if there are no card details in the Element
        document.querySelector("button").disabled = event.empty;
        document.querySelector("#card-error").textContent = event.error ? event.error.message : "";
      });

      var form = document.getElementById("payment-form");
      form.addEventListener("submit", function(event) {
        event.preventDefault();
        // Complete payment when the submit button is clicked

        fetch("{% url 'purchase:payment' %}", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            'X-CSRFToken': csrftoken
          },
          
          body: JSON.stringify({
            family_kanji: document.getElementById('family_kanji').value,
            last_kanji: document.getElementById('last_kanji').value,
            family_kana: document.getElementById('family_kana').value,
            last_kana: document.getElementById('last_kana').value,
            email: document.getElementById('email').value,
            tel:document.getElementById('tel').value,
            yuubin: document.getElementById('yuubin').value,
            todoufuken: document.getElementById('todoufuken').value,
            shikuchouson: document.getElementById('shikuchouson').value,
            buildingname: document.getElementById('buildingname').value,
            totalPrice: document.getElementById("total-price").innerHTML,
            sub_totalPrice: document.getElementById("sub_total_price").innerHTML,
            shippingPrice: document.getElementById("price_shipping").innerHTML,
            discountPrice: document.getElementById("discount-price").innerHTML,
            
          })
          
        })
          .then(function(result) {
            return result.json();
          })
          .then(function(data) {
            payWithCard(stripe, card, data.clientSecret);
          });
      });
      
      var payWithCard = function(stripe, card, clientSecret) {
        loading(true);
        stripe
          .confirmCardPayment(clientSecret, {
            payment_method: {
              card: card
            }
          })
          .then(function(result) {
            if (result.error) {
              // Show error to your customer
              showError(result.error.message);
            } else {
              // The payment succeeded!
              orderComplete(result.paymentIntent.id);
            }
          });
      };

      /* ------- UI helpers ------- */
      // Shows a success message when the payment is complete
      var orderComplete = function(paymentIntentId) {
        console.log(paymentIntentId)
        loading(false);
        document.querySelector(".result-message a").setAttribute(
            "href",
            "https://dashboard.stripe.com/test/payments/" + paymentIntentId
          );
        document.querySelector(".result-message").classList.remove("hidden");
        document.querySelector("button").disabled = true;
        location.href='{% url "purchase:complate" %}';

      };
      // Show the customer the error from Stripe if their card fails to charge
      var showError = function(errorMsgText) {
        loading(false);
        var errorMsg = document.querySelector("#card-error");
        errorMsg.textContent = errorMsgText;
        setTimeout(function() {
          errorMsg.textContent = "";
        }, 4000);
      };
      // Show a spinner on payment submission
      var loading = function(isLoading) {
        if (isLoading) {
          // Disable the button and show a spinner
          document.querySelector("button").disabled = true;
          document.querySelector("#spinner").classList.remove("hidden");
          document.querySelector("#button-text").classList.add("hidden");
        } else {
          document.querySelector("button").disabled = false;
          document.querySelector("#spinner").classList.add("hidden");
          document.querySelector("#button-text").classList.remove("hidden");
        }
      };

  </script> 

{% endblock %}

purchase/templates/thx.html
{% extends "base.html" %}
{% load static %}

{% block metadescription %}
    This is the shopping cart page.. Proced to review your items and place the order.
{% endblock %}

{% block title %}KUMAGAI KITCHEN | ご購入完了{% endblock %}
{% block content %}

  <main class="main-area-fadein">
      <div class="thx_page ">
        <div class="complete-moji">
          <a>お支払いが完了しました</a>
          <p>通常、2〜3営業日以内に発送いたします。</p>
          <p>商品の到着までしばらくお待ちくださいませ。</p>
          <div >
            <a href="{% url 'shop:allProdCat' %}" class="link-under-line"><span class="to_top_page_ad"> 商品一覧へ</span></a>
          </div>
        </div>
        
      </div>

  </main>
  {% include 'footer.html' %}
 {% endblock %}