cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

ec1/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.topfunc,name="top"),
    path('shop/', include('shop.urls')), 
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('purchase/', include('purchase.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),
    path("guide/",views.howtofunc,name="howto"),
    path("asct/",views.asctfunc,name="asct"),
    path("privacy-policy/",views.ppfunc,name="pp"),
    path("faq/",views.faqfunc,name="faq"),
    path("aboutus/",views.aboutfunc,name="aboutus"),
     path('contactform/',views.contactfunc,name="sendmail"),
    path('donecontact/',views.contactcomplete,name="donecontact"),

]

if settings.DEBUG:
    # staticファイルとmediaファイルのドキュメントルートを設定
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
     path('thanks/<int:order_id>/', views.thanks, name='thanks'),
     path('history/', views.orderHistory, name='order_history'),
     path('<int:order_id>/', views.viewOrder, name='order_detail'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('',views.allProdCat,name="allProdCat"),
    path("<slug:c_slug>/",views.allProdCat,name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

class ShippingPrice(models.Model):
    area_name = models.CharField("エリア名",max_length=20,unique=True)
    shipping_price = models.IntegerField("配送料")
    description = models.TextField("エリア説明",blank=True)
    

    class Meta:
        ordering = ('area_name',)
        verbose_name_plural = "配送料"
    
    def __str__(self):
        return self.area_name

    


class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="category",blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "カテゴリー"

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return "{}".format(self.name)


class Product(models.Model):
    name = models.CharField("商品名",max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField("商品説明",blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    price = models.PositiveIntegerField("価格")
    inTax = models.PositiveIntegerField("内消費税",default=200)
    image = models.ImageField("TOP画像",upload_to="product",blank=True)
    stock = models.IntegerField("在庫")
    available = models.BooleanField(default=True)
    created = models.DateTimeField("作成日",auto_now_add=True)
    updated = models.DateTimeField("変更日",auto_now=True)

    cartDescription = models.TextField("カート用説明", max_length=100,blank=True)#New)
    image2 = models.ImageField("画像2枚目",upload_to="product",blank=True)#New
    image3 = models.ImageField("画像3枚目",upload_to="product",blank=True)#New
    hoverImage = models.ImageField("ホバー画像",upload_to="product",blank=True)#New
    cookingUrl = models.CharField("調理動画",max_length=10000,blank=True)#New

    descriptionTitle1 = models.CharField("説明タイトル1",max_length=255, blank=True)#New
    descriptionContent1 = models.TextField("説明内容1",blank=True)#New
    descriptionImage1 = models.ImageField("説明画像1",upload_to="product", blank=True)#New

    descriptionTitle2 = models.CharField("説明タイトル2",max_length=255, blank=True)#New
    descriptionContent2 = models.TextField("説明タイトル2",blank=True)#New
    descriptionImage2 = models.ImageField("説明画像2",upload_to="product",blank=True)#New

    descriptionTitle3 = models.CharField("説明タイトル3",max_length=255,blank=True)#New
    descriptionContent3 = models.TextField("説明内容3",blank=True)#New
    descriptionImage3 = models.ImageField("説明画像3",upload_to="product",blank=True)#New

    descriptionTitle4 = models.CharField("説明タイトル4",max_length=255,blank=True)#New
    descriptionContent4 = models.TextField("説明内容4",blank=True)#New
    descriptionImage4 = models.ImageField("説明画像4",upload_to="product",blank=True)#New
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = "商品データ"


    def get_url(self):
        return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])


    def __str__(self):
        return str(self.name)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=254, help_text='eq. youremail@anyemail.com')

    class Meta:
        model = User
        fields = {'first_name', 'last_name', 'username', 'password1', 'password2'}

shop/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from .models import Category,Product,ShippingPrice
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.core.mail import BadHeaderError, send_mail


def topfunc(request):
    return render(request,"top.html")

def howtofunc(request):
    return render(request,"howto.html")

def asctfunc(request):
    return render(request,"asct.html")

def ppfunc(request):
    return render(request,"privacy-policy.html")

def faqfunc(request):
    return render(request,"faq.html")

def aboutfunc(request):
    return render(request,"contact.html")

def signoutView(request):
    logout(request)
    return redirect('signin')

def contactcomplete(request):
    return render(request, 'complete.html')




def signinView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('shop:allProdCat')
            else:
                return redirect('signup')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/signin.html', {'form': form})


def signupView(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            signup_user = User.objects.get(username=username)
            customer_group = Group.objects.get(name='Customer')
            customer_group.user_set.add(signup_user)
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})



def index(request):
    text_var ="This is my first django app web page."
    return HttpResponse(text_var)

def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    paginator = Paginator(products_list, 12)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pags)
    return render(request, 'shop/category.html', {'category': c_page, 'products': products})


def allWine(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        c_page = "winebar"
        products_list = Product.objects.all().filter(available=True)

    paginator = Paginator(products_list, 12)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pags)
    return render(request, 'shop/category.html', {'category': c_page, 'products': products})



def ProdCatDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'shop/product.html', {'product': product})


def contactfunc(request):
    if request.method == 'POST':
        recipient_list = ["shikata@kumagaicorp.jp"]#送信先
        from_email = "kitchen@kumagaicorp.jp"#メールに表示されるfrom

        sender = request.POST['email']
        subject = sender+" さんからの問い合わせ"
        content_title = "【 "+request.POST['title']+" 】"
        content = request.POST['message']
        message = content_title + content
        # from_email = "kitchen@kumagaicorp.jp"
        # recipient_list = ["kumagaicorppress@gmail.com"]
        # subject = "テスト送信"
        # message = "初めてのメール送信"
        # from_email = "kintai@kumagaicorp.jp"

        send_mail(subject, message, from_email,recipient_list)
      
        return redirect('donecontact')
   
    return render(request, 'contact.html')

shop/templates/asct.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content%}
  <div class="content-area main-section-fadein">
      <div class="asct-area">
        <div class="top-asct">
          <a class="asct-title">特定商取引法に基づく表示</a>
        </div>
        <div class="asct-content">
          <ul class="asct-list">
            <li class="asct-item"><b>販売サービス名称</b><p>KUMAGAI KITCHEN</p></li>
            <li class="asct-item"><b>運営統括責任者</b><p>熊谷　康夫</p></li>
            <li class="asct-item"><b>運営会社</b><p>クマガイコーポレーション株式会社</p></li>
            <li class="asct-item"><b>運営会社の所在地</b><p>〒150-0041　<br />東京都渋谷区神南1-20-15 和田ビル5階</p></li>
            <li class="asct-item"><b>運営会社の電話番号</b><p>03-3461-2652</p></li>
            <li class="asct-item"><b>メールアドレス</b><p>kitchen@kumagaicorp.jp</p></li>
            <li class="asct-item"><b>販売URL</b><p></p></li>
            <li class="asct-item"><b>販売価格</b><p>各商品による</p></li>
            <li class="asct-item"><b>お支払い方法</b><p>クレジットカードまたはデビットカード</p></li>
            <li class="asct-item"><b>商品代金以外の必要金額</b><p>・消費税<br/>・送料：本州880円〜沖縄：2,160円</p></li>
            <li class="asct-item"><b>販売数量</b><p>1個から</p></li>
            <li class="asct-item"><b>商品引渡し時期</b><p>決済完了確認後3営業日以内で発送致します。</p></li>
            <li class="asct-item"><b>商品引渡し方法</b><p>ヤマト運輸 宅急便 クール便 冷凍便</p></li>
            <li class="asct-item"><b>返品・不良品について</b><p>「不良品・当社の商品の間違い」の場合は当社が負担いたします。<br /> 配送途中の破損などの事故がございましたら、弊社までご連絡下さい。<br /> 送料・手数料ともに弊社負担で早急に新品をご送付致します。<br /><br /> 【返品対象】<br />「不良品・当社の商品の間違い」の場合<br /><br /> 【返品時期】<br />ご購入後2日以内にご連絡があった場合に返金可能となります。<br /><br /> 【返品方法】<br />メールにて返金要請してください。<br />4日以内にご購入代金を指定の口座へお振込みいたします。</p></li>
            <li class="asct-item"><b>表現、及び商品に関する注意書き</b><p>本商品に示された表現や再現性には個人差があり、<br />必ずしも利益や効果を保証したものではございません。</p></li>
        <!--
            <li class="asct-item"><b></b><p></p></li>-->
          </ul>
        </div>
      </div>
    </div>
   {% include 'footer.html' %}
{% endblock content%}

shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
  <head>
    <meta charset="utf-8">
	  <meta name="description" content="{% block metadescription %}{% endblock %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link rel="stylesheet" href="{% static 'css/fv_responce_style.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css">
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@300&display=swap" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">
        
  </head>
  <body>
 
        {% include 'navbar.html' %}
       
        {% block content %}
        {% endblock %}
	
   <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
   <script src="{% static 'js/script2.js' %}"></script>
  
  </body>
</html>

shop/templates/complete.html
{% extends "base.html" %}
{% load static %}

{% block metadescription %}
    This is the shopping cart page.. Proced to review your items and place the order.
{% endblock %}

{% block title %}KUMAGAI KITCHEN | 問い合わせ完了{% endblock %}
{% block content %}

  <main class="main-area-fadein">
      <div class="thx_page ">
        <div class="complete-moji">
          <a>問い合わせがが完了しました</a>
          

          <div >
            <a href="{% url 'shop:allProdCat' %}" class="link-under-line"><span class="to_top_page_ad"> 商品一覧へ</span></a>
          </div>
        </div>
        
      </div>

  </main>
  {% include 'footer.html' %}
 {% endblock %}

shop/templates/contact.html
{% extends "base.html" %}
{% load static %}


{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
KUMAGAI KITCHEN | 問い合わせ
{% endblock %}
{% block content %}
<div class="content-area main-section-fadein">
      
      <div class="contact-area">
        <div class="top-contact">
          <a class="contact-title">問い合わせ</a>
        </div>
        <div class="contact-form">
          <form id="contact" action="{% url 'sendmail' %}" method="post">
            {% csrf_token %}
            <div class="form-container">
              <!-- <input class="contact-input" type="text" name="name" placeholder="お名前" /><br /> -->
              <input  class="contact-input" type="email" name="email" placeholder="メールアドレス"  required></input><br />
              <input class="contact-input" type="text" name="title" placeholder="件名"  required></input><br />
              <textarea type="text" name="message" placeholder="問い合わせ内容"  required></textarea><br />
              
              <button id="submit" type="submit">
                送信
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
    {% include 'footer.html' %}
   

{% endblock %}

shop/templates/faq.html
{% extends 'base.html' %}
{% load static %}

{% block title %}KUMAGAI KITCHEN | FAQ{% endblock %}
{% block content%}
<div class="content-area main-section-fadein">
      <div class="faq-title">
        <a>よくある質問</a>
      </div>
      <div class="faq-menu">
          <label class="faq-label" for="faq1">Q . どのぐらいで届きますか?</label>
          <input type="checkbox" id="faq1" class="on-off" />
          <ul>
              <li><a>通常であれば3営業日以内に発送いたします。<br>ご自宅に届くまでは1週間を目処にお届けいたします</a></li>
          </ul>
          <label class="faq-label" for="faq2">ここに質問が入ります</label>
          <input type="checkbox" id="faq2" class="on-off" />
          <ul>
              <li><a>ここに回答が入ります</a></li>
          </ul>
          <label class="faq-label" for="faq3">ここに質問が入ります</label>
          <input type="checkbox" id="faq3" class="on-off" />
          <ul>
              <li><a>ここに回答が入ります</a></li>
          </ul>
          <label class="faq-label" for="faq4">ここに質問が入ります</label>
          <input type="checkbox" id="faq4" class="on-off" />
          <ul>
              <li><a>ここに回答が入ります</a></li>
          </ul>
          
      </div>
    </div>
    {% include 'footer.html' %}
    {% endblock content%}

shop/templates/footer.html
{% load static %}
    
    <footer class="company-info">
      <div class="shop-thumbnail">
        <div class="thumbnail-area">
          <div class="child-thumbnail"><img src="{% static 'img/logo_bio.gif' %}" alt="BiOcafeのロゴ"></div>
          <div class="child-thumbnail"><img src="{% static 'img/logo_bistrogourmand.gif' %}" alt="ビストロ グルマンのロゴ"></div>
          <div class="child-thumbnail"><img src="{% static 'img/logo_chiocciola.gif' %}" alt="キオッチョラ ピッツェリアのロゴ"></div>
          <div class="child-thumbnail"><img src="{% static 'img/logo_lasoffitta.gif' %}" alt="ラ・ソフィッタのロゴ"></div>
          <div class="child-thumbnail"><img src="{% static 'img/logo_yamashiroyashozo.gif' %}" alt="山城屋庄蔵のロゴ"></div>
          <div class="child-thumbnail"><img src="{% static 'img/logo_ningenkankei.gif' %}" alt="人間関係のロゴ"></div>
        </div>
      </div>
      <div class="info-line">
          <div class="b-line"></div>
        </div>
      <div class="info-area">
        <div class="kk-info">
          <a class="footer-title">KUMAGAI KITCHEN</a>
          <p>渋谷で創業107年、お店で紡いできた歴史を<br>
              全国へお届けいたします。</p>
        </div>
        <div class="kk-infomation">
          <div class="help-link">
            <a class="footer-title">HELP</a>
            <ul class="info-list helplist">
              <li class="info-item"><a class="link-under-line" href="{% url 'howto' %}">ご利用方法</a></li>
              <li class="info-item"><a class="link-under-line" href="{% url 'asct' %}">特定商取引法に基づく表記</a></li>
              <li class="info-item"><a class="link-under-line" href="{% url 'pp' %}">ブライパシーポリシー</a></li>
              <li class="info-item"><a class="link-under-line" href="{% url 'aboutus' %}">問い合わせ</a></li>
              <li class="info-item"><a class="link-under-line" href="{% url 'faq' %}">FAQ</a></li>
            </ul>
          </div>
          <div class="kc-info">
            <a class="footer-title">運営会社</a>
            <ul class="info-list">
              <li class="info-item"><a href=""><i class="fas fa-building icon-size"></i>&nbsp;&nbsp;クマガイコーポレーション株式会社</a></li>
              <li class="info-item"><a href=""><i class="fas fa-map-marked-alt icon-size"></i>&nbsp;&nbsp;東京都渋谷区神南1-20-15 和田ビル5階</a></li>
              <li class="info-item"><a href=""><i class="fas fa-phone-square-alt"></i>&nbsp;&nbsp; 03-3461-2652</a></li>
              <li class="info-item"><a href=""><i class="fas fa-envelope"></i>&nbsp;&nbsp;kitchen@kumagaicorp.jp</a></li>
            </ul>
          </div>
        </div>
        
      
      </div>
      <div class="info-line">
          <div class="b-line"></div>
        </div>
      <div class="c-right">
        <p >Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved KUMAGAICORPORATION</a></p>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

shop/templates/navbar.html
{% load static %}
    
	<header >
      <div class="header-area fadein-target">
        <div class="header-item-area ">
          <a class="top-logo" href="{% url 'top' %}"><img src="{% static 'img/kumagai4_1.png' %}" alt="KUMAGAIKITCHEN"></a>
          <nav class="header-nav">
            <ul class="gnav" id="header-item-list">
                <li class="link-under-line">
                  <a><span class="fontRound ">BRANDS</span></a>
                  <ul class="child-list">
                    {% for cat in links %}
                      <li class="gchild-item link-under-line"><a href="{{cat.get_url}}">{{cat.name}}</a></li>
                    {% endfor %} 
                  </ul>
                </li>
                <li class="link-under-line"><a href="{% url 'shop:allProdCat' %}"><span class="fontRound ">ITEMS</span></a></li>
				        <li class="link-under-line">
                  {% if request.user.is_authenticated and request.user.first_name %}
                    <a><span class="fontRound ">{{ request.user.first_name }} </span></a>
                    <ul class="child-list">
                        <li class="gchild-item link-under-line"><a href="{% url 'order:order_history' %}" >購入履歴</a></li>
                        <li class="gchild-item link-under-line"><a href="{% url 'signout' %}">ログアウト</a></li>
                    </ul>
                  {% else %}
                    <a><span class="fontRound ">MEMBER</span></a>
                    <ul class="child-list">
                      <li class="gchild-item link-under-line"><a href="{% url 'signup' %}">新規登録</a></li>
                      <li class="gchild-item link-under-line"><a href="{% url 'signin' %}">ログイン</a></li>
                    </ul>
                  {% endif %}
                </li>
                <li class="link-under-line"><a href="{% url 'cart:cart_detail' %}" ><span class="fontRound ">CART</span>[ {{item_count}} ]</a></li>
            </ul>
          </nav>
        </div>
      </div>      
  </header> 
    
    <div id="navArea">
        <nav class="sp-nav">
          <div class="inner">
            <ul>
              <li>
                <input id="brands-check" class="acd-check" type="checkbox">
                <label class="acd-label" for="brands-check">BRANDS</label>
                <div class="acd-content">
                  {% for cat in links %}
                    <p href="{{cat.get_url}}">{{cat.name}}</p>
                  {% endfor %}
                </div>
              </li>
              <li><a href="{% url 'shop:allProdCat' %}">ITEMS</a></li>
              <li>
                <input id="acd-check1" class="acd-check" type="checkbox">
                {% if request.user.is_authenticated and request.user.first_name %}
                  <label class="acd-label" for="acd-check1">{{ request.user.first_name }}</label>
                  <div class="acd-content">
                    <p href="{% url 'order:order_history' %}">購入履歴</p>
                    <p href="{% url 'signout' %}">ログアウト</p>
                  </div>
                {% else %}
                  <label class="acd-label" for="acd-check1">MEMBER</label>
                  <div class="acd-content">
                    <p href="{% url 'signup' %}">新規登録</p>
                    <p href="{% url 'signin' %}">ログイン</p>
                  </div>
                {% endif %}
                  
              </li>
              <li ><a href="{% url 'cart:cart_detail' %}" >CART[{{item_count}}]</a></li>
              <li><a href="{% url 'aboutus' %}">CONTACT</a></li>
            </ul>
          </div>
          <div class="side-c-right">
              <p >Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved KUMAGAICORPORATION</a></p>
          </div>
        </nav>
        <div class="toggle_btn fadein-target">
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div id="mask"></div>
      </div>