cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

ec1/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.topfunc,name="top"),
    path('shop/', include('shop.urls')), 
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('purchase/', include('purchase.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),
    path("guide/",views.howtofunc,name="howto"),
    path("asct/",views.asctfunc,name="asct"),
    path("privacy-policy/",views.ppfunc,name="pp"),
    path("faq/",views.faqfunc,name="faq"),
    path("aboutus/",views.aboutfunc,name="aboutus"),
     path('contactform/',views.contactfunc,name="sendmail"),
    path('donecontact/',views.contactcomplete,name="donecontact"),

]

if settings.DEBUG:
    # staticファイルとmediaファイルのドキュメントルートを設定
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchase/urls.py
from django.urls import path
from . import views

app_name = 'purchase'

urlpatterns = [
    path('',views.purchasefunc, name='purchase'),
    path('complate/',views.complete,name="complate"),
    path('payment/', views.create_payment, name='payment'),
   
   
]

cart/models.py
from django.db import models
from shop.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

cart/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from order.models import Order, OrderItem

def cart_detail(request, total=0, tax=0,counter=0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            tax += (cart_item.product.inTax * cart_item.quantity)
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    # stripe.api_key = settings.STRIPE_SECRET_KEY

    return render(request, 'cart.html', dict(cart_items = cart_items, total = total, tax=tax, counter = counter))



def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
                cart_id =  _cart_id(request)
            )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart
            )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')



cart/templates/cart.html
{% extends "base.html" %}
{% load static %}

{% block metadescription %}
    This is the shopping cart page.. Proced to review your items and place the order.
{% endblock %}
{% block title %}KUMAGAI KITCHEN | カート{% endblock %}
{% block content %}

    
	{% if not cart_items %}
        <section id="cart">
          <div class="text-center">
            <h1 class="text center my_title">買い物かごの中身は空です</h1>
            <br>
          
                <a href="{% url 'top' %}" class="to_top">TOPへ</a>
            
          </div>
		</section>
		{% include 'footer.html' %}
    {% else %}
		<div class="container main-area-fadein">
        	<section id="cart"> 
				{% for cart_item in cart_items %}
					<article class="product">
					<header>
					<a href="{{cart_item.product.get_url}}"><img src="{% static cart_item.product.image.url %}" alt=""></a>
					</header>
					<div class="content b-border">
					<h1 href="{{cart_item.product.get_url}}">{{cart_item.product.name}}</h1>
					{{ cart_item.product.cartDescription | linebreaksbr}}
					<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="sp-remove">×</a>
					
					</div>
					<footer class="content">
						<a href="{% url 'cart:cart_remove' cart_item.product.id %}"><span class="qt-minus">-</span></a>
						<span class="qt">{{cart_item.quantity}} </span>
						<a  href="{% url 'cart:add_cart' cart_item.product.id %}"><span class="qt-plus">+</span></a>
						<h3 class="full-price">{{cart_item.sub_total}}<span>円</span></h3>
						<h2 class="price">{{cart_item.product.price }}<span>円</span>
					</footer>
				</article>
				{% endfor %}
			</section>
	    </div>
		<footer id="site-footer">
			<div class="container clearfix">
				<div class="purchase-area">
					<table class="price-table">
						<tr>
						<td>小計</td>
						<td></td>
						<td class="subtotal"><span>{{ total }}</span>円</td>
						</tr>
						<tr>
						<td></td>
						<td>内消費税  </td>
						<td class="tax"><span>{{ tax  }}</span>円</td>
						</tr>
						
						<tr>
						<td>割引</td>
						<td>記念割引</td>
						<td><span>0</span>円</td>
						</tr>
					</table>
					<div class="total-price">
						<h1 class="total"  id="total-amount">小計 : <span>{{ total }}</span>円<p class="tax-in-text">(税込)</p></h1>
						
					</div>
				</div>
				<div class="purchase"> <a class="btn" href="{% url 'purchase:purchase' %}">決済情報入力</a></div>
			</div>
		</footer>
	
	{% endif %}
{% comment %} 	
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>		
	 <script src="{% static 'js/cart.js' %}"></script> {% endcomment %}
{% endblock %}